feat: improve tests and fix python version
- Improve test coverage for FundMe contract with eth balance checks
- Use hypothesis for generating random addresses and amounts
- Updated pyproject.toml to support Python >=3.13 -> issues with 3.12 (need investigation?)

```
➜ mox compile
Running compile command...
Compiling 2 contracts to out/...
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/s3bc40/perso-projects/web3-portfolio/moccasin/.venv/lib/python3.12/site-packages/moccasin/commands/compile.py", line 228, in compile_noret
    compile_(*args, **kwargs)
  File "/home/s3bc40/perso-projects/web3-portfolio/moccasin/.venv/lib/python3.12/site-packages/moccasin/commands/compile.py", line 170, in compile_
    deployer: VyperDeployer | VVMDeployer = load_partial(
                                            ^^^^^^^^^^^^^
  File "/home/s3bc40/perso-projects/web3-portfolio/moccasin/.venv/lib/python3.12/site-packages/boa/interpret.py", line 287, in load_partial
    return loads_partial(
           ^^^^^^^^^^^^^^
  File "/home/s3bc40/perso-projects/web3-portfolio/moccasin/.venv/lib/python3.12/site-packages/boa/interpret.py", line 281, in loads_partial
    data = compiler_data(source_code, name, filename, deployer_class, **compiler_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s3bc40/perso-projects/web3-portfolio/moccasin/.venv/lib/python3.12/site-packages/boa/interpret.py", line 176, in compiler_data
    return _disk_cache.caching_lookup(cache_key, get_compiler_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s3bc40/perso-projects/web3-portfolio/moccasin/.venv/lib/python3.12/site-packages/boa/util/disk_cache.py", line 71, in caching_lookup
    return pickle.loads(f.read())
           ^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pathlib._local'; 'pathlib' is not a package
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/s3bc40/perso-projects/web3-portfolio/moccasin/.venv/bin/mox", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/s3bc40/perso-projects/web3-portfolio/moccasin/.venv/lib/python3.12/site-packages/moccasin/__init__.py", line 8, in main
    __main__.main(sys.argv[1:])
  File "/home/s3bc40/perso-projects/web3-portfolio/moccasin/.venv/lib/python3.12/site-packages/moccasin/__main__.py", line 58, in main
    import_module(f"moccasin.commands.{command_to_run}").main(args)
  File "/home/s3bc40/perso-projects/web3-portfolio/moccasin/.venv/lib/python3.12/site-packages/moccasin/commands/compile.py", line 51, in main
    compile_project(
  File "/home/s3bc40/perso-projects/web3-portfolio/moccasin/.venv/lib/python3.12/site-packages/moccasin/commands/compile.py", line 144, in compile_project
    job.get()
  File "/usr/lib/python3.12/multiprocessing/pool.py", line 774, in get
    raise self._value
ModuleNotFoundError: No module named 'pathlib._local'; 'pathlib' is not a package

```

-